# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch
  
jobs:
  build:
    name: Build Project
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
        
    - name: Restore dependencies
      run: dotnet restore -v detailed
      
    - name: Build
      run: dotnet build -c Release

    - name: Upload build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: .output/
